/**
 * File: 005_sales.sql
 * Purpose: Create sales and sale_items tables for invoice management with GST breakdown
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates:
 * 1. sales table - Invoice headers with GST breakdown and payment tracking
 * 2. sale_items table - Line items for each invoice with item-level GST
 */

-- Create sales table
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  
  -- Invoice Information
  invoice_number TEXT,
  invoice_type TEXT DEFAULT 'regular' CHECK (invoice_type IN ('regular', 'gst', 'gst_export')),
  
  -- Amount Breakdown
  subtotal NUMERIC(12, 2) NOT NULL,
  discount_amount NUMERIC(12, 2) DEFAULT 0.00,
  
  -- GST Breakdown (only populated for GST invoices)
  taxable_amount NUMERIC(12, 2) DEFAULT 0.00,
  cgst_amount NUMERIC(12, 2) DEFAULT 0.00,
  sgst_amount NUMERIC(12, 2) DEFAULT 0.00,
  igst_amount NUMERIC(12, 2) DEFAULT 0.00,
  total_tax_amount NUMERIC(12, 2) DEFAULT 0.00,
  
  total_amount NUMERIC(12, 2) NOT NULL,
  
  -- Payment Information
  payment_method TEXT DEFAULT 'cash' CHECK (payment_method IN ('cash', 'upi', 'card', 'credit')),
  payment_status TEXT DEFAULT 'paid' CHECK (payment_status IN ('paid', 'partial', 'credit')),
  amount_paid NUMERIC(12, 2) DEFAULT 0.00,
  balance_due NUMERIC(12, 2) DEFAULT 0.00,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create sale_items table
CREATE TABLE IF NOT EXISTS sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product_serial_id BIGINT REFERENCES product_serials(id) ON DELETE SET NULL,
  
  -- Item Details
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10, 2) NOT NULL,
  discount_amount NUMERIC(10, 2) DEFAULT 0.00,
  
  -- GST per Item (for detailed GST reporting)
  hsn_code TEXT,
  taxable_amount NUMERIC(12, 2) DEFAULT 0.00,
  cgst_percent NUMERIC(5, 2) DEFAULT 0.00,
  cgst_amount NUMERIC(12, 2) DEFAULT 0.00,
  sgst_percent NUMERIC(5, 2) DEFAULT 0.00,
  sgst_amount NUMERIC(12, 2) DEFAULT 0.00,
  igst_percent NUMERIC(5, 2) DEFAULT 0.00,
  igst_amount NUMERIC(12, 2) DEFAULT 0.00,
  
  total_price NUMERIC(12, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_sales_user_id ON sales(user_id);
CREATE INDEX idx_sales_customer_id ON sales(customer_id);
CREATE INDEX idx_sales_created_at ON sales(created_at);
CREATE INDEX idx_sales_payment_status ON sales(payment_status) WHERE payment_status != 'paid';
CREATE INDEX idx_sale_items_sale_id ON sale_items(sale_id);
CREATE INDEX idx_sale_items_product_id ON sale_items(product_id);

-- Enable Row Level Security
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;

-- Sales RLS Policies
CREATE POLICY "Users can view own sales"
  ON sales FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own sales"
  ON sales FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sales"
  ON sales FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own sales"
  ON sales FOR DELETE
  USING (auth.uid() = user_id);

-- Sale Items RLS Policies
CREATE POLICY "Users can view own sale items"
  ON sale_items FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own sale items"
  ON sale_items FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sale items"
  ON sale_items FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own sale items"
  ON sale_items FOR DELETE
  USING (auth.uid() = user_id);

-- Triggers
CREATE TRIGGER update_sales_updated_at
  BEFORE UPDATE ON sales
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Function to automatically update product stock after sale
CREATE OR REPLACE FUNCTION update_stock_on_sale()
RETURNS TRIGGER AS $$
BEGIN
  -- Decrease stock quantity when sale item is created
  UPDATE products
  SET stock_quantity = stock_quantity - NEW.quantity
  WHERE id = NEW.product_id;
  
  -- Mark serial as sold if applicable
  IF NEW.product_serial_id IS NOT NULL THEN
    UPDATE product_serials
    SET status = 'sold',
        sale_id = NEW.sale_id
    WHERE id = NEW.product_serial_id;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update stock when sale is created
CREATE TRIGGER update_stock_after_sale
  AFTER INSERT ON sale_items
  FOR EACH ROW
  EXECUTE FUNCTION update_stock_on_sale();

COMMENT ON TABLE sales IS 'Sales/invoices with full GST breakdown and payment tracking';
COMMENT ON TABLE sale_items IS 'Line items for sales with item-level GST details';
/**
 * File: 006_purchase_orders.sql
 * Purpose: Create purchase_orders table for managing supplier orders
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the purchase_orders table to track orders placed with suppliers.
 */

-- Create purchase_orders table
CREATE TABLE IF NOT EXISTS purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  
  po_number TEXT,
  items JSONB NOT NULL, -- Array of {product_id, product_name, quantity, unit_price}
  
  subtotal NUMERIC(12, 2) DEFAULT 0.00,
  tax_amount NUMERIC(12, 2) DEFAULT 0.00,
  total_amount NUMERIC(12, 2) DEFAULT 0.00,
  
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'ordered', 'received', 'cancelled')),
  
  expected_date DATE,
  received_date DATE,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_purchase_orders_user_id ON purchase_orders(user_id);
CREATE INDEX idx_purchase_orders_supplier_id ON purchase_orders(supplier_id);
CREATE INDEX idx_purchase_orders_status ON purchase_orders(status);

ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own POs"
  ON purchase_orders FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own POs"
  ON purchase_orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own POs"
  ON purchase_orders FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own POs"
  ON purchase_orders FOR DELETE
  USING (auth.uid() = user_id);

CREATE TRIGGER update_purchase_orders_updated_at
  BEFORE UPDATE ON purchase_orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE purchase_orders IS 'Purchase orders to suppliers';
/**
 * File: 007_drafts.sql
 * Purpose: Create draft tables for AI-generated invoices, inventory batches, and purchase orders
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates draft tables that store AI-generated data awaiting user approval.
 */

-- Draft invoices (AI-generated bills awaiting approval)
CREATE TABLE IF NOT EXISTS draft_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name TEXT,
  
  items JSONB NOT NULL, -- Array of {product_id, product_name, quantity, unit_price, total}
  total_amount NUMERIC(12, 2) NOT NULL,
  payment_method TEXT DEFAULT 'cash',
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Draft inventory batches (bulk product imports from Excel/images)
CREATE TABLE IF NOT EXISTS draft_inventory_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  source_type TEXT CHECK (source_type IN ('image', 'file', 'manual')),
  source_name TEXT,
  items JSONB DEFAULT '[]'::jsonb, -- Array of product data from OCR/Excel
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Draft purchase orders (AI-generated POs)
CREATE TABLE IF NOT EXISTS draft_purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  supplier_name TEXT,
  
  items JSONB NOT NULL,
  total_amount NUMERIC(12, 2),
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_draft_invoices_user_id ON draft_invoices(user_id);
CREATE INDEX idx_draft_invoices_status ON draft_invoices(status);
CREATE INDEX idx_draft_inventory_batches_user_id ON draft_inventory_batches(user_id);
CREATE INDEX idx_draft_inventory_batches_status ON draft_inventory_batches(status);
CREATE INDEX idx_draft_purchase_orders_user_id ON draft_purchase_orders(user_id);
CREATE INDEX idx_draft_purchase_orders_status ON draft_purchase_orders(status);

-- Enable RLS
ALTER TABLE draft_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE draft_inventory_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE draft_purchase_orders ENABLE ROW LEVEL SECURITY;

-- RLS Policies for draft_invoices
CREATE POLICY "Users can manage own draft invoices"
  ON draft_invoices FOR ALL
  USING (auth.uid() = user_id);

-- RLS Policies for draft_inventory_batches
CREATE POLICY "Users can manage own draft batches"
  ON draft_inventory_batches FOR ALL
  USING (auth.uid() = user_id);

-- RLS Policies for draft_purchase_orders
CREATE POLICY "Users can manage own draft POs"
  ON draft_purchase_orders FOR ALL
  USING (auth.uid() = user_id);

COMMENT ON TABLE draft_invoices IS 'AI-generated invoice drafts awaiting approval';
COMMENT ON TABLE draft_inventory_batches IS 'Bulk inventory imports from files/images';
COMMENT ON TABLE draft_purchase_orders IS 'AI-generated purchase order drafts';
/**
 * File: 008_inventory_logs.sql
 * Purpose: Create inventory_logs table for tracking all stock changes
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the inventory_logs table as an audit trail
 * for all inventory changes (sales, purchases, adjustments, returns).
 */

-- Create inventory_logs table
CREATE TABLE IF NOT EXISTS inventory_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  
  change_type TEXT NOT NULL CHECK (change_type IN ('sale', 'purchase', 'adjustment', 'return')),
  quantity_change INTEGER NOT NULL, -- Positive for additions, negative for reductions
  previous_quantity INTEGER,
  new_quantity INTEGER,
  
  -- Reference to the transaction that caused this change
  reference_type TEXT, -- 'sale', 'purchase_order', 'manual'
  reference_id BIGINT,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_inventory_logs_user_id ON inventory_logs(user_id);
CREATE INDEX idx_inventory_logs_product_id ON inventory_logs(product_id);
CREATE INDEX idx_inventory_logs_created_at ON inventory_logs(created_at);
CREATE INDEX idx_inventory_logs_change_type ON inventory_logs(change_type);

-- Enable RLS
ALTER TABLE inventory_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own inventory logs"
  ON inventory_logs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own inventory logs"
  ON inventory_logs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE inventory_logs IS 'Audit trail for all inventory changes';

