/**
 * File: 001_profiles.sql
 * Purpose: Create user profiles table with business information and GST settings
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the profiles table which stores business owner information,
 * GST registration details, voice preferences, and subscription tier.
 */

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  business_name TEXT,
  owner_name TEXT,
  whatsapp_number TEXT,
  business_category TEXT CHECK (business_category IN ('kirana', 'medical', 'hardware')),
  business_address TEXT,
  
  -- GST Information
  gstin TEXT, -- GST Identification Number
  is_gst_registered BOOLEAN DEFAULT false,
  state_code TEXT, -- For CGST/SGST calculation (e.g., '27' for Maharashtra)
  
  -- AI Customization
  gpt_instructions TEXT, -- Custom instructions for AI behavior
  
  -- Voice Settings
  voice_id TEXT DEFAULT 'hi-IN-MadhurNeural', -- Default Hindi voice
  voice_speed TEXT DEFAULT '+0%',
  language_pref TEXT DEFAULT 'hi-IN', -- Default language preference
  
  -- Subscription
  subscription_tier TEXT DEFAULT 'free' CHECK (subscription_tier IN ('free', 'starter', 'pro', 'ultra')),
  
  -- Onboarding Status
  onboarding_completed BOOLEAN DEFAULT false,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX idx_profiles_business_category ON profiles(business_category);
CREATE INDEX idx_profiles_is_gst_registered ON profiles(is_gst_registered);

-- Enable Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only view/edit their own profile
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE profiles IS 'User business profiles with GST and voice settings';
/**
 * File: 002_suppliers.sql
 * Purpose: Create suppliers table for managing vendor information
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the suppliers table to track vendor details,
 * payment terms, and GSTIN for business-to-business transactions.
 */

-- Create suppliers table
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Supplier Information
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  address TEXT,
  gstin TEXT, -- Supplier's GST number for B2B transactions
  
  -- Business Terms
  payment_terms TEXT, -- e.g., "Net 30 days", "Cash on delivery"
  notes TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster searches
CREATE INDEX idx_suppliers_user_id ON suppliers(user_id);
CREATE INDEX idx_suppliers_name ON suppliers(name);

-- Enable Row Level Security
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Users can only manage their own suppliers
CREATE POLICY "Users can view own suppliers"
  ON suppliers FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own suppliers"
  ON suppliers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own suppliers"
  ON suppliers FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own suppliers"
  ON suppliers FOR DELETE
  USING (auth.uid() = user_id);

-- Trigger to auto-update updated_at
CREATE TRIGGER update_suppliers_updated_at
  BEFORE UPDATE ON suppliers
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE suppliers IS 'Supplier/vendor management for purchase orders';
/**
 * File: 003_products.sql
 * Purpose: Create products and product_serials tables for inventory management
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates:
 * 1. products table - Main product catalog with pricing, tax, warranty info
 * 2. product_serials table - Individual tracking of IMEI/serial numbers for electronics
 */

-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Basic Information
  name TEXT NOT NULL,
  description TEXT,
  sku TEXT, -- Stock Keeping Unit
  barcode TEXT,
  category TEXT,
  
  -- Pricing
  cost_price NUMERIC(10, 2) DEFAULT 0, -- Purchase price
  selling_price NUMERIC(10, 2) NOT NULL, -- Retail price
  mrp NUMERIC(10, 2), -- Maximum Retail Price (for labeling)
  
  -- GST/Tax Information
  hsn_code TEXT, -- HSN/SAC code for GST
  tax_percent NUMERIC(5, 2) DEFAULT 0, -- Total GST percentage (e.g., 18.00)
  cgst_percent NUMERIC(5, 2) DEFAULT 0, -- Central GST
  sgst_percent NUMERIC(5, 2) DEFAULT 0, -- State GST
  igst_percent NUMERIC(5, 2) DEFAULT 0, -- Integrated GST (for inter-state)
  
  discount NUMERIC(5, 2) DEFAULT 0, -- Default discount percentage
  
  -- Inventory Management
  stock_quantity INTEGER DEFAULT 0,
  min_stock_level INTEGER DEFAULT 5, -- Alert when stock falls below this
  unit TEXT DEFAULT 'pcs', -- Unit of measurement: pcs, kg, ltr, box, etc.
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  
  -- For Medical/Grocery Stores
  expiry_date DATE, -- Product expiration date
  batch_number TEXT, -- Manufacturing batch number
  
  -- For Hardware/Electronics Stores
  warranty_months INTEGER DEFAULT 0, -- Warranty period in months
  has_serial_tracking BOOLEAN DEFAULT false, -- Enable individual item tracking
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create product_serials table for individual item tracking
CREATE TABLE IF NOT EXISTS product_serials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  
  -- Serial/IMEI Information
  serial_number TEXT,
  imei_number TEXT,
  
  -- Warranty Tracking
  warranty_start_date DATE,
  warranty_end_date DATE,
  
  -- Status Tracking
  status TEXT DEFAULT 'in_stock' CHECK (status IN ('in_stock', 'sold', 'returned', 'damaged')),
  sale_id BIGINT, -- Reference to sale when sold
  customer_id BIGINT, -- Reference to customer when sold
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_products_user_id ON products(user_id);
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_stock_quantity ON products(stock_quantity);
CREATE INDEX idx_products_expiry_date ON products(expiry_date) WHERE expiry_date IS NOT NULL;
CREATE INDEX idx_product_serials_product_id ON product_serials(product_id);
CREATE INDEX idx_product_serials_status ON product_serials(status);
CREATE INDEX idx_product_serials_serial_number ON product_serials(serial_number) WHERE serial_number IS NOT NULL;

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_serials ENABLE ROW LEVEL SECURITY;

-- Products RLS Policies
CREATE POLICY "Users can view own products"
  ON products FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own products"
  ON products FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own products"
  ON products FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own products"
  ON products FOR DELETE
  USING (auth.uid() = user_id);

-- Product Serials RLS Policies
CREATE POLICY "Users can view own serials"
  ON product_serials FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own serials"
  ON product_serials FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own serials"
  ON product_serials FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own serials"
  ON product_serials FOR DELETE
  USING (auth.uid() = user_id);

-- Triggers
CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_product_serials_updated_at
  BEFORE UPDATE ON product_serials
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE products IS 'Product catalog with pricing, GST, warranty, and inventory data';
COMMENT ON TABLE product_serials IS 'Individual tracking for serialized items (IMEI/serial numbers)';
/**
 * File: 004_customers.sql
 * Purpose: Create customers table for client management with credit tracking
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the customers table to manage customer information,
 * purchase history, and credit balance (khata/udhar) tracking.
 */

-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Customer Information
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  address TEXT,
  
  -- Financial Tracking
  total_spend NUMERIC(12, 2) DEFAULT 0.00, -- Lifetime spending
  credit_balance NUMERIC(12, 2) DEFAULT 0.00, -- Outstanding credit/udhar amount
  
  -- Engagement Tracking
  last_visit TIMESTAMPTZ,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster searches
CREATE INDEX idx_customers_user_id ON customers(user_id);
CREATE INDEX idx_customers_phone ON customers(phone) WHERE phone IS NOT NULL;
CREATE INDEX idx_customers_name ON customers(name);
CREATE INDEX idx_customers_credit_balance ON customers(credit_balance) WHERE credit_balance > 0;

-- Enable Row Level Security
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own customers"
  ON customers FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own customers"
  ON customers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own customers"
  ON customers FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own customers"
  ON customers FOR DELETE
  USING (auth.uid() = user_id);

-- Trigger
CREATE TRIGGER update_customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE customers IS 'Customer management with credit/khata tracking';

