/**
 * File: 003_products.sql
 * Purpose: Create products and product_serials tables for inventory management
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates:
 * 1. products table - Main product catalog with pricing, tax, warranty info
 * 2. product_serials table - Individual tracking of IMEI/serial numbers for electronics
 */

-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Basic Information
  name TEXT NOT NULL,
  description TEXT,
  sku TEXT, -- Stock Keeping Unit
  barcode TEXT,
  category TEXT,
  
  -- Pricing
  cost_price NUMERIC(10, 2) DEFAULT 0, -- Purchase price
  selling_price NUMERIC(10, 2) NOT NULL, -- Retail price
  mrp NUMERIC(10, 2), -- Maximum Retail Price (for labeling)
  
  -- GST/Tax Information
  hsn_code TEXT, -- HSN/SAC code for GST
  tax_percent NUMERIC(5, 2) DEFAULT 0, -- Total GST percentage (e.g., 18.00)
  cgst_percent NUMERIC(5, 2) DEFAULT 0, -- Central GST
  sgst_percent NUMERIC(5, 2) DEFAULT 0, -- State GST
  igst_percent NUMERIC(5, 2) DEFAULT 0, -- Integrated GST (for inter-state)
  
  discount NUMERIC(5, 2) DEFAULT 0, -- Default discount percentage
  
  -- Inventory Management
  stock_quantity INTEGER DEFAULT 0,
  min_stock_level INTEGER DEFAULT 5, -- Alert when stock falls below this
  unit TEXT DEFAULT 'pcs', -- Unit of measurement: pcs, kg, ltr, box, etc.
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  
  -- For Medical/Grocery Stores
  expiry_date DATE, -- Product expiration date
  batch_number TEXT, -- Manufacturing batch number
  
  -- For Hardware/Electronics Stores
  warranty_months INTEGER DEFAULT 0, -- Warranty period in months
  has_serial_tracking BOOLEAN DEFAULT false, -- Enable individual item tracking
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create product_serials table for individual item tracking
CREATE TABLE IF NOT EXISTS product_serials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  
  -- Serial/IMEI Information
  serial_number TEXT,
  imei_number TEXT,
  
  -- Warranty Tracking
  warranty_start_date DATE,
  warranty_end_date DATE,
  
  -- Status Tracking
  status TEXT DEFAULT 'in_stock' CHECK (status IN ('in_stock', 'sold', 'returned', 'damaged')),
  sale_id BIGINT, -- Reference to sale when sold
  customer_id BIGINT, -- Reference to customer when sold
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_products_user_id ON products(user_id);
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_stock_quantity ON products(stock_quantity);
CREATE INDEX idx_products_expiry_date ON products(expiry_date) WHERE expiry_date IS NOT NULL;
CREATE INDEX idx_product_serials_product_id ON product_serials(product_id);
CREATE INDEX idx_product_serials_status ON product_serials(status);
CREATE INDEX idx_product_serials_serial_number ON product_serials(serial_number) WHERE serial_number IS NOT NULL;

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_serials ENABLE ROW LEVEL SECURITY;

-- Products RLS Policies
CREATE POLICY "Users can view own products"
  ON products FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own products"
  ON products FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own products"
  ON products FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own products"
  ON products FOR DELETE
  USING (auth.uid() = user_id);

-- Product Serials RLS Policies
CREATE POLICY "Users can view own serials"
  ON product_serials FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own serials"
  ON product_serials FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own serials"
  ON product_serials FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own serials"
  ON product_serials FOR DELETE
  USING (auth.uid() = user_id);

-- Triggers
CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_product_serials_updated_at
  BEFORE UPDATE ON product_serials
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE products IS 'Product catalog with pricing, GST, warranty, and inventory data';
COMMENT ON TABLE product_serials IS 'Individual tracking for serialized items (IMEI/serial numbers)';
