/**
 * File: 004_customers.sql
 * Purpose: Create customers table for client management with credit tracking
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the customers table to manage customer information,
 * purchase history, and credit balance (khata/udhar) tracking.
 */

-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Customer Information
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  address TEXT,
  
  -- Financial Tracking
  total_spend NUMERIC(12, 2) DEFAULT 0.00, -- Lifetime spending
  credit_balance NUMERIC(12, 2) DEFAULT 0.00, -- Outstanding credit/udhar amount
  
  -- Engagement Tracking
  last_visit TIMESTAMPTZ,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster searches
CREATE INDEX idx_customers_user_id ON customers(user_id);
CREATE INDEX idx_customers_phone ON customers(phone) WHERE phone IS NOT NULL;
CREATE INDEX idx_customers_name ON customers(name);
CREATE INDEX idx_customers_credit_balance ON customers(credit_balance) WHERE credit_balance > 0;

-- Enable Row Level Security
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own customers"
  ON customers FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own customers"
  ON customers FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own customers"
  ON customers FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own customers"
  ON customers FOR DELETE
  USING (auth.uid() = user_id);

-- Trigger
CREATE TRIGGER update_customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE customers IS 'Customer management with credit/khata tracking';
