/**
 * File: 006_purchase_orders.sql
 * Purpose: Create purchase_orders table for managing supplier orders
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the purchase_orders table to track orders placed with suppliers.
 */

-- Create purchase_orders table
CREATE TABLE IF NOT EXISTS purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  
  po_number TEXT,
  items JSONB NOT NULL, -- Array of {product_id, product_name, quantity, unit_price}
  
  subtotal NUMERIC(12, 2) DEFAULT 0.00,
  tax_amount NUMERIC(12, 2) DEFAULT 0.00,
  total_amount NUMERIC(12, 2) DEFAULT 0.00,
  
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'ordered', 'received', 'cancelled')),
  
  expected_date DATE,
  received_date DATE,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_purchase_orders_user_id ON purchase_orders(user_id);
CREATE INDEX idx_purchase_orders_supplier_id ON purchase_orders(supplier_id);
CREATE INDEX idx_purchase_orders_status ON purchase_orders(status);

ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own POs"
  ON purchase_orders FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own POs"
  ON purchase_orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own POs"
  ON purchase_orders FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own POs"
  ON purchase_orders FOR DELETE
  USING (auth.uid() = user_id);

CREATE TRIGGER update_purchase_orders_updated_at
  BEFORE UPDATE ON purchase_orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE purchase_orders IS 'Purchase orders to suppliers';
