/**
 * File: 007_drafts.sql
 * Purpose: Create draft tables for AI-generated invoices, inventory batches, and purchase orders
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates draft tables that store AI-generated data awaiting user approval.
 */

-- Draft invoices (AI-generated bills awaiting approval)
CREATE TABLE IF NOT EXISTS draft_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name TEXT,
  
  items JSONB NOT NULL, -- Array of {product_id, product_name, quantity, unit_price, total}
  total_amount NUMERIC(12, 2) NOT NULL,
  payment_method TEXT DEFAULT 'cash',
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Draft inventory batches (bulk product imports from Excel/images)
CREATE TABLE IF NOT EXISTS draft_inventory_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  source_type TEXT CHECK (source_type IN ('image', 'file', 'manual')),
  source_name TEXT,
  items JSONB DEFAULT '[]'::jsonb, -- Array of product data from OCR/Excel
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Draft purchase orders (AI-generated POs)
CREATE TABLE IF NOT EXISTS draft_purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  supplier_name TEXT,
  
  items JSONB NOT NULL,
  total_amount NUMERIC(12, 2),
  
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_draft_invoices_user_id ON draft_invoices(user_id);
CREATE INDEX idx_draft_invoices_status ON draft_invoices(status);
CREATE INDEX idx_draft_inventory_batches_user_id ON draft_inventory_batches(user_id);
CREATE INDEX idx_draft_inventory_batches_status ON draft_inventory_batches(status);
CREATE INDEX idx_draft_purchase_orders_user_id ON draft_purchase_orders(user_id);
CREATE INDEX idx_draft_purchase_orders_status ON draft_purchase_orders(status);

-- Enable RLS
ALTER TABLE draft_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE draft_inventory_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE draft_purchase_orders ENABLE ROW LEVEL SECURITY;

-- RLS Policies for draft_invoices
CREATE POLICY "Users can manage own draft invoices"
  ON draft_invoices FOR ALL
  USING (auth.uid() = user_id);

-- RLS Policies for draft_inventory_batches
CREATE POLICY "Users can manage own draft batches"
  ON draft_inventory_batches FOR ALL
  USING (auth.uid() = user_id);

-- RLS Policies for draft_purchase_orders
CREATE POLICY "Users can manage own draft POs"
  ON draft_purchase_orders FOR ALL
  USING (auth.uid() = user_id);

COMMENT ON TABLE draft_invoices IS 'AI-generated invoice drafts awaiting approval';
COMMENT ON TABLE draft_inventory_batches IS 'Bulk inventory imports from files/images';
COMMENT ON TABLE draft_purchase_orders IS 'AI-generated purchase order drafts';
