/**
 * File: 008_inventory_logs.sql
 * Purpose: Create inventory_logs table for tracking all stock changes
 * Author: Dukan Sathi Team
 * Created: 2026-02-05
 * 
 * This migration creates the inventory_logs table as an audit trail
 * for all inventory changes (sales, purchases, adjustments, returns).
 */

-- Create inventory_logs table
CREATE TABLE IF NOT EXISTS inventory_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  
  change_type TEXT NOT NULL CHECK (change_type IN ('sale', 'purchase', 'adjustment', 'return')),
  quantity_change INTEGER NOT NULL, -- Positive for additions, negative for reductions
  previous_quantity INTEGER,
  new_quantity INTEGER,
  
  -- Reference to the transaction that caused this change
  reference_type TEXT, -- 'sale', 'purchase_order', 'manual'
  reference_id BIGINT,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_inventory_logs_user_id ON inventory_logs(user_id);
CREATE INDEX idx_inventory_logs_product_id ON inventory_logs(product_id);
CREATE INDEX idx_inventory_logs_created_at ON inventory_logs(created_at);
CREATE INDEX idx_inventory_logs_change_type ON inventory_logs(change_type);

-- Enable RLS
ALTER TABLE inventory_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own inventory logs"
  ON inventory_logs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own inventory logs"
  ON inventory_logs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

COMMENT ON TABLE inventory_logs IS 'Audit trail for all inventory changes';
